cask "agent-notch" do # THE FILE IS GENERATED BY scripts/build_release.sh
  version "0.1.0"
  sha256 "e2b7c0a7b3704b26fa2eebafede096749e49662777e6da394e8258643372d0f4"

  url "https://github.com/tosaka07/agent-notch/releases/download/v#{version}/AgentNotch-v#{version}-macos-arm64.zip"
  name "Agent Notch"
  desc "Notch-based command center for AI coding agents"
  homepage "https://github.com/tosaka07/agent-notch"

  depends_on macos: :tahoe
  depends_on arch: :arm64

  app "AgentNotch-v#{version}/AgentNotch.app"

  # Link the CLI inside the installed app rather than the copy under bin/.
  # A bare executable cannot carry a stapled notarization ticket, but the one
  # inside AgentNotch.app is covered by the ticket stapled to the bundle.
  binary "#{appdir}/AgentNotch.app/Contents/MacOS/agent-notch"
end
