cask "agent-notch" do # THE FILE IS GENERATED BY scripts/build_release.sh
  version "0.1.3"
  sha256 "fceb3927f82c40e1782ec16ad22bfed9bce04afff19d58339b9ad2b461f229c3"

  url "https://github.com/tosaka07/agent-notch/releases/download/v#{version}/AgentNotch-v#{version}-macos-arm64.zip"
  name "Agent Notch"
  desc "Notch-based command center for AI coding agents"
  homepage "https://github.com/tosaka07/agent-notch"

  depends_on macos: :tahoe
  depends_on arch: :arm64

  app "AgentNotch-v#{version}/AgentNotch.app"

  # Link the CLI inside the installed app rather than the copy under bin/.
  # A bare executable cannot carry a stapled notarization ticket, but the one
  # inside AgentNotch.app is covered by the ticket stapled to the bundle.
  binary "#{appdir}/AgentNotch.app/Contents/MacOS/agent-notch"
end
