cask "agent-notch" do # THE FILE IS GENERATED BY scripts/build_release.sh
  version "0.1.2"
  sha256 "2bc05131feecd2df095c4f509e6506a296db8a54b0881579691f15ea309de201"

  url "https://github.com/tosaka07/agent-notch/releases/download/v#{version}/AgentNotch-v#{version}-macos-arm64.zip"
  name "Agent Notch"
  desc "Notch-based command center for AI coding agents"
  homepage "https://github.com/tosaka07/agent-notch"

  depends_on macos: :tahoe
  depends_on arch: :arm64

  app "AgentNotch-v#{version}/AgentNotch.app"

  # Link the CLI inside the installed app rather than the copy under bin/.
  # A bare executable cannot carry a stapled notarization ticket, but the one
  # inside AgentNotch.app is covered by the ticket stapled to the bundle.
  binary "#{appdir}/AgentNotch.app/Contents/MacOS/agent-notch"
end
